version: 2
updates:
  - package-ecosystem: maven
    directory: /apps/api
    schedule:
      interval: weekly
    groups:
      backend-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
