package io.github.yanziki.enterpriseai.tenant;

public enum WorkspaceOperation {
    READ_METADATA,
    DOWNLOAD_ORIGINAL,
    UPLOAD_DOCUMENT,
    CREATE_VERSION,
    ARCHIVE_DOCUMENT,
    RETRY_INGESTION,
    SEARCH_CONTENT,
    ANSWER_FROM_KNOWLEDGE,
    CREATE_REVIEW_CASE,
    VIEW_REVIEW_CASES,
    MANAGE_REVIEW_CASES,
    INSPECT_RETRIEVAL
}
