package io.github.yanziki.enterpriseai.retrieval;

public enum RetrievalFailureCode {
    CHUNKING_FAILURE,
    CHUNK_LIMIT_EXCEEDED,
    EMBEDDING_PROVIDER_UNAVAILABLE,
    EMBEDDING_TIMEOUT,
    EMBEDDING_RESPONSE_INVALID,
    EMBEDDING_DIMENSION_MISMATCH,
    INDEX_PERSISTENCE_FAILURE,
    INTERNAL_INDEXING_ERROR
}
